// Builds src/logos.js from the simple-icons package (CC0 shapes). Brands simple-icons
// doesn't have get a coloured badge with their short name instead.
import { writeFileSync } from 'node:fs';
import * as si from 'simple-icons';

const BRANDS = [
  // id, name, matcher, simple-icons export or text badge, colours
  ['paypal', 'PayPal', /pay\s?pal/i, 'siPaypal'],
  ['dkb', 'DKB', /\bdkb\b/i, { text: 'DKB', bg: '#148DEA' }],
  ['traderepublic', 'Trade Republic', /trade\s?republic/i, { text: 'TR', bg: '#000000' }],
  ['binance', 'Binance', /binance/i, 'siBinance', '#1E2026'],
  ['kraken', 'Kraken', /kraken/i, { text: 'K', bg: '#7132F5' }],
  ['coinbase', 'Coinbase', /coinbase/i, 'siCoinbase'],
  ['bitpanda', 'Bitpanda', /bitpanda/i, { text: 'B', bg: '#27D17F', fg: '#0B1F14' }],
  ['scalable', 'Scalable Capital', /scalable/i, { text: 'SC', bg: '#1F2B37' }],
  ['revolut', 'Revolut', /revolut/i, 'siRevolut'],
  ['n26', 'N26', /\bn26\b/i, 'siN26', '#1D1D1D'],
  ['sparkasse', 'Sparkasse', /sparkasse/i, 'siSparkasse'],
  ['volksbank', 'Volksbank', /volksbank|raiffeisen/i, { text: 'VR', bg: '#0066B3' }],
  ['ing', 'ING', /\bING\b|ing-diba/, { text: 'ING', bg: '#FF6200' }],
  ['comdirect', 'Comdirect', /comdirect/i, { text: 'c', bg: '#FFF500', fg: '#111111' }],
  ['commerzbank', 'Commerzbank', /commerzbank/i, 'siCommerzbank', '#002E3C'],
  ['deutschebank', 'Deutsche Bank', /deutsche\s?bank/i, 'siDeutschebank'],
  ['postbank', 'Postbank', /postbank/i, { text: 'PB', bg: '#FFCC00', fg: '#0A2896' }],
  ['c24', 'C24', /\bc24\b/i, { text: 'C24', bg: '#0A3A6B' }],
  ['wise', 'Wise', /\bwise\b/i, 'siWise', '#163300'],
];

const light = (hex) => {
  const n = parseInt(hex.slice(1), 16);
  return (0.299 * (n >> 16) + 0.587 * ((n >> 8) & 255) + 0.114 * (n & 255)) > 170;
};

const out = BRANDS.map(([id, name, re, src, bgOverride]) => {
  if (typeof src === 'string') {
    const icon = si[src];
    if (!icon) throw new Error('missing ' + src);
    const color = '#' + icon.hex;
    // Keep the brand colour on the tile; for very light brand colours draw the mark dark.
    const bg = bgOverride && light(color) ? color : bgOverride ? bgOverride : color;
    const fg = bgOverride && !light(color) ? color : light(bg) ? '#111111' : '#FFFFFF';
    return { id, name, re: re.toString(), bg, fg, path: icon.path };
  }
  return { id, name, re: re.toString(), bg: src.bg, fg: src.fg || '#FFFFFF', text: src.text };
});

const body = out.map((b) => `  { id: ${JSON.stringify(b.id)}, name: ${JSON.stringify(b.name)}, re: ${b.re}, bg: '${b.bg}', fg: '${b.fg}', ${b.path ? `path: ${JSON.stringify(b.path)}` : `text: ${JSON.stringify(b.text)}`} },`).join('\n');
writeFileSync('src/logos.js', `// Generated by scripts/logos.mjs. Shapes from simple-icons (CC0); brand names and marks belong to their owners.
export const BRANDS = [
${body}
];

export const brandById = (id) => BRANDS.find((b) => b.id === id) || null;

// acc.brand: a brand id, 'none' for initials, or unset to detect it from the name.
export function brandOf(acc) {
  if (acc.brand === 'none') return null;
  if (acc.brand) return brandById(acc.brand);
  return BRANDS.find((b) => b.re.test(acc.name || '')) || null;
}

export function logoSvg(brand) {
  if (brand.path) return \`<svg viewBox="0 0 24 24" width="20" height="20" fill="\${brand.fg}" aria-hidden="true"><path d="\${brand.path}"/></svg>\`;
  return \`<span class="logo-text" style="color:\${brand.fg}">\${brand.text}</span>\`;
}
`);
console.log('wrote', out.length, 'brands');
